version: "3.8"
services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0-xenial
    container_name: mongoEmpl
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-expressEmplo
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - elk_network
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk_network
    ports:
      - "5000:5000"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    ports:
      - "5601:5601"
    networks:
      - elk_network
    depends_on:
      - elasticsearch

volumes:
  data: { }

networks:
  mongodb_network:
    name: mongodb_network
  elk_network:
    driver: bridge
