version: "3.8"
services:
  backend:
    build: .
    restart: always
    environment:
      - MONGO_HOST=mongodb
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0-xenial
    container_name: mongoEmpl
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-expressEmplo
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - default
  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    volumes:
      #      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    networks:
      - default
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - default
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/config.yml
    command:
      - '--config.file=/etc/prometheus/config.yml'


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ./loki/promtail.yml:/etc/promtail/promtail.yml
      - /var/log/:/var/log:ro
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
volumes:
  grafana-storage: { }
  elasticsearch_data:
    driver: local

networks:
  default:
    name: spring
    driver: bridge
