version: "3.8"
services:
  backend:
    build: .
    restart: always
    ports:
      - 5001:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0-xenial
    container_name: mongoEmpl
    ports:
      - 27017:27017
      #    volumes:
      #      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
#  mongo-express:
#    image:
#      mongo-express:latest
#    container_name: mongo-expressEmplo
#    restart: always
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongodb
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#
#volumes:
#  data: { }
#
#networks:
#  default:
#    name: mongodb_network
