version: "3.8"
services:
  backend:
    build: .
    restart: always
    environment:
      - MONGO_HOST=mongodb
    ports:
      - "${SRV_PORT:-8080}"
    depends_on:
      - mongodb
    networks:
      - default

  mongodb:
    image: mongo:4.0-xenial
    container_name: mongoEmpl
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-expressEmplo
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - default
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/application.log:/var/log/application.log
    depends_on:
      - elasticsearch
    networks:
      - default
    ports:
      - "5000:5000"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    ports:
      - "5601:5601"
    networks:
      - default
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/config.yml
    command:
      - '--config.file=/etc/prometheus/config.yml'


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default:
    external:
      name: spring
