spring:
  application:
    name: Employer-CRUD
  data:
    mongodb:
      port: 27017
      database: employer
      host: ${MONGO_HOST}

  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    function:
      definition: mergeEmployersWithProducts
    stream:
      bindings:
        mergeEmployersWithProducts-in-0:
          destination: products
          content-type: application/json
        mergeEmployersWithProducts-out-0:
          destination: products.out
          content-type: application/json
      kafka:
        streams:
          binder:
            functions:
              mergeEmployersWithProducts:
                applicationId: mergeProducts
          bindings:
            mergeEmployersWithProducts-in-1:
              consumer:
                materializedAs: products-store
  main:
    allow-circular-references: true

springdoc.swagger-ui.path: /swagger-ui.html
server:
  port: 8085

useLogstash: false
useLoki: false

mqtt:
  broker:
    url: tcp://mqtt-broker:1883
  client:
    id: client-1
  topic: my/topic



management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/employer
server:
  port: 8080
