spring:
  application:
    name: Employer-CRUD
  data:
    mongodb:
      port: 27017
      database: employer
      host: ${MONGO_HOST}

  main:
    allow-circular-references: true

springdoc.swagger-ui.path: /swagger-ui.html
server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      port: 27017
      database: employer
      host: localhost
