spring:
  application:
    name: Employer-CRUD
  data:
    mongodb:
      port: 27017
      database: employer
      host: localhost
      username: rootuser
      password: rootpass
      authentication-database: admin
  main:
    allow-circular-references: true

springdoc.swagger-ui.path: /swagger-ui.html
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    jmx:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
